<a href="https://colab.research.google.com/github/Sleeveso/CSTD-Repo/blob/main/dataPreprocessing_cleaned_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [100]:
#importing modules/libries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [101]:
#importing datasets
df = pd.read_csv('StudentsPerformance.csv')
cat_cols = df.columns[:5]
df[cat_cols] = df[cat_cols].apply(lambda x: x.str.strip().str.lower())
# x = df.iloc[:,  :-1].values
x = df.drop(df.columns[5], axis=1)
#x = df.drop(df.columns[4], axis=1).iloc[:, :].values
y = df.iloc[:,  5].values
# df.info()
# print(df.isnull().sum())

In [88]:
print(x)

[[ 1.  0.  0. ...  0. 72. 74.]
 [ 1.  0.  0. ...  1. 90. 88.]
 [ 1.  0.  0. ...  0. 95. 93.]
 ...
 [ 1.  0.  0. ...  1. 71. 65.]
 [ 1.  0.  0. ...  1. 78. 77.]
 [ 1.  0.  0. ...  0. 86. 86.]]


In [53]:
from sklearn.impute import SimpleImputer

In [102]:
#filling missing data
imputer = SimpleImputer(missing_values= np.nan, strategy= 'mean')
#use nan to detect not numbers and replace them with coloumn 'mean'(or "median", "most_frequent", "constant")
# imputer.fit(x[:, 6:])
# x[:, 6:] = imputer.transform(x[:, 6:])
x.iloc[:, 6:] = imputer.fit_transform(x.iloc[:, 6:])


In [55]:
print(x)

[['female' 'group b' "bachelor's degree" ... 72 72 74.0]
 ['female' 'group c' 'some college' ... 69 90 88.0]
 ['female' 'group b' "master's degree" ... 90 95 93.0]
 ...
 ['female' 'group c' 'high school' ... 59 71 65.0]
 ['female' 'group d' 'some college' ... 68 78 77.0]
 ['female' 'group d' 'some college' ... 77 86 86.0]]


Encoding categorical data

In [103]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(handle_unknown="ignore"), list(range(4))),
                                     ("binary", OrdinalEncoder(categories=[["none", "completed"]]), [4])],
                       remainder='passthrough')
x = np.array(ct.fit_transform(x))
# x = np.array(ct.fit_transform(df.drop(df.columns[5], axis=1)))

In [107]:
print(x)

[[ 1.  0.  0. ...  0. 72. 74.]
 [ 1.  0.  0. ...  1. 90. 88.]
 [ 1.  0.  0. ...  0. 95. 93.]
 ...
 [ 1.  0.  0. ...  1. 71. 65.]
 [ 1.  0.  0. ...  1. 78. 77.]
 [ 1.  0.  0. ...  0. 86. 86.]]


In [92]:
print(y[:5])

[72 69 90 47 76]
